In [9]:
import numpy as np

step 1:
Encoding and separating the data using numpy 

In [10]:
data = [
    [150, 7.0, 1, 'Apple'],
    [120, 6.5, 0, 'Banana'],
    [180, 7.5, 2, 'Orange'],
    [155, 7.2, 1, 'Apple'],
    [110, 6.0, 0, 'Banana'],
    [190, 7.8, 2, 'Orange'],
    [145, 7.1, 1, 'Apple'],
    [115, 6.3, 0, 'Banana']
]
data

[[150, 7.0, 1, 'Apple'],
 [120, 6.5, 0, 'Banana'],
 [180, 7.5, 2, 'Orange'],
 [155, 7.2, 1, 'Apple'],
 [110, 6.0, 0, 'Banana'],
 [190, 7.8, 2, 'Orange'],
 [145, 7.1, 1, 'Apple'],
 [115, 6.3, 0, 'Banana']]

In [11]:
labels = {"Apple" : 0, "Banana" : 1,"Orange" : 2}

In [12]:
X = np.array([x[0:3] for x in data])
print(X)


#normalising X:
mean= np.mean(X , axis = 0)                                             #axis = 0 means mean col wise ie mean per feature while axis = 1 means mean row-wise
std= np.std(X , axis = 0)
X_scaled = (X - mean)/std
print(X_scaled)

[[150.    7.    1. ]
 [120.    6.5   0. ]
 [180.    7.5   2. ]
 [155.    7.2   1. ]
 [110.    6.    0. ]
 [190.    7.8   2. ]
 [145.    7.1   1. ]
 [115.    6.3   0. ]]
[[ 0.15815423  0.13068205  0.16012815]
 [-0.92633194 -0.74053163 -1.12089708]
 [ 1.24264041  1.00189574  1.44115338]
 [ 0.33890193  0.47916753  0.16012815]
 [-1.28782733 -1.61174531 -1.12089708]
 [ 1.6041358   1.52462395  1.44115338]
 [-0.02259346  0.30492479  0.16012815]
 [-1.10707964 -1.0890171  -1.12089708]]


In [13]:
y = np.array([labels[x[-1]] for x in data])
y

array([0, 1, 2, 0, 1, 2, 0, 1])

STEP 2: WRITING THE EUCLIDEAN FUNCTION

In [14]:
def euclidean_distance (a,b):
    return np.sqrt(np.sum((a-b)**2))
    

STEP 3 : MAKING THE CLASS FOR KNN

In [15]:
class KNN: 
    def __init__(self,k = 3):
        self.k = k

    def fit (self,X,y):
        self.X = X
        self.y = y
    
    def predict_one(self,x):
        distances = [euclidean_distance(y,x) for y in self.X]
        indices = np.argsort(distances)
        nearest_k = indices[0:self.k]
        nearest_k_labels = self.y[nearest_k]
        values , counts = np.unique(nearest_k_labels,return_counts=True)
        max_index = np.argmax(counts)
        max_value = values[max_index]
        return max_value
    
    def predict (self,X_test):
        return [self.predict_one(t) for t in X_test]



STEP 4:TESTING THE SAMPLE

In [16]:
test_data = np.array([
    [118, 6.2 , 0],  # Expected: Banana
    [160, 7.3, 1],  # Expected: Apple
    [185, 7.7, 2]   # Expected: Orange
])
model = KNN(k=3)
model.fit (X_scaled,y)

#normalising the test_data :

test_data_scaled = (test_data - mean)/std



reverse_labels = {v: k for k, v in labels.items()}
ans = [reverse_labels[x] for x in model.predict(test_data_scaled)]
print(ans)


['Banana', 'Apple', 'Orange']
